### ISSUE TITLE
Getting duplicate subjects, come in random, don't break the interface

### ISSUE THREAD

**Issue by yshish** [zooniverse/chimpandsee#103]
Some videos come to be classified more than once by the same user. They come in random (for example 2 days after the 1st classification) and the browser console shows no errors. We recognize them due to the comments we made after the 1st classification. It is an old problem which happens to various volunteers.

Some examples:
http://talk.chimpandsee.org/#/subjects/ACP00062ny
http://talk.chimpandsee.org/#/subjects/ACP0007bsa
http://talk.chimpandsee.org/#/subjects/ACP0007frf
http://talk.chimpandsee.org/#/subjects/ACP0006t2k
http://talk.chimpandsee.org/#/subjects/ACP0007p0n
http://talk.chimpandsee.org/#/subjects/ACP0007ey9
http://talk.chimpandsee.org/#/subjects/ACP0007zcx
http://talk.chimpandsee.org/#/subjects/ACP0007fly
http://talk.chimpandsee.org/#/subjects/ACP000asl3

**Comment by yshish** [comment]
I created a tag group for them http://talk.chimpandsee.org/#/collections/CCPL0000o9
It will collect all videos hashtagged with 'repeated'.

**Comment by astopy** [comment]
This will be the same problem as #132.
