### ISSUE TITLE
"This Type of Video File is Not Supported"

### ISSUE THREAD

**Issue by AnLand** [zooniverse/chimpandsee#123]
Hi, several users complaint recently that videos are not playing. Message: "This Type of Video File is Not Supported". A particular problem seems to be the Edge browser of the current Windows version. Could you please look into that and maybe give advice (if cannot be solved)? Thanks!

**Comment by shaunanoordin** [comment]
Issue: Edge browsers on Windows 10 cannot play videos on Chimp & See.
Analysis: Edge does not like the C&S videos to be from a HTTP source.

Changing the video player code from...
```
<video width="400" src="http://www.chimpandsee.org/subjects/56b1f9388f7532000190d661/56b1f9388f7532000190d661.mp4" controls="" poster="http://www.chimpandsee.org/subjects/56b1f9388f7532000190d661/previews/56b1f9388f7532000190d661_0.jpg" type="video/mp4">Your browser does not support the video format. Please upgrade your browser.</video>
```
...to...
```
<video width="400" src="https://www.chimpandsee.org/subjects/56b1f9388f7532000190d661/56b1f9388f7532000190d661.mp4" controls="" poster="http://www.chimpandsee.org/subjects/56b1f9388f7532000190d661/previews/56b1f9388f7532000190d661_0.jpg" type="video/mp4">Your browser does not support the video format. Please upgrade your browser.</video>
```
...allows the video to be played.

Note that there is **no issue** with the MP4 file itself, despite the "This Type of Video File is Not Supported" message; this can be tested by downloading the MP4 to a local system and plonking it into a simple .html with a player.

Solution: The video sources in Chimp & See need to be changed to HTTPS.

Status: Solution to be implemented
