### ISSUE TITLE
"We're out of data" message wrongly displayed

### ISSUE THREAD

**Issue by AnLand** [zooniverse/chimpandsee#124]
Hi! While classifying I get the "We're out of data" message displayed repeatedly. We're not out of data. Refreshing the page brings new videos for a while. I emptied my cache and started Firefox anew repeatedly. Is there any problem with the site?

I cannot say whether other people have the same problem, but we have suspiciously few classifications today.

**Comment by yshish** [comment]
Yes, it is a known problem which affects several volunteers in old projects. 
It has been reported under PP https://github.com/zooniverse/planktonportal/issues/52 and then here: https://github.com/zooniverse/planktonportal/issues/31
@srallen was looking at that.
I was experiencing it very often (daily) for several months. I don't classify much lately so I can't tell whether something has changed for me.

**Comment by AnLand** [comment]
Can it be that we are out of data for Cold Fire? (Or any other problem with this site?)

**Comment by AnLand** [comment]
Error message: "Laden von gemischten aktiven Inhalten "http://zooniverse-demo.s3-website-us-east-1.amazonaws.com/projects.js?_=1462370978392" wurde blockiert." (Mixed content ...)

https://code.jquery.com/jquery-1.11.0.min.js (row 4, column 27353)

**Comment by srallen** [comment]
@AnLand the JQuery error has to do with a broken project listing in the footer. I'll have a deployed fix up shortly.

As for the 'out of data' message, this is a difficult issue for us to track, however, it looks like something is going wrong as there are 20,000+ active subjects across a couple of subject groups. I'll take a look this morning.

**Comment by jwidness** [comment]
I've classified over 200 videos since Cold Fire ran out without running into the out of data message -- BUT, I can easily force the message to show up by refreshing the classification page a few times.  I would guess that the problem stems from the fact that Cold Fire's state is still active?

Side question: since we seem to often run into this bug when sites finish, could we possibly change the wording of the out of data message to suggest refreshing the page?

**Comment by AnLand** [comment]
@srallen Yes, I thought that these are two different problems, but I'm only getting this single errror message. Videos from Restless Star and Dawn Bird are working apparently, but I did not have one from Cold Fire and the pattern of the "We're out of data" message looks like an attempted switch to Cold Fire that failed. But I cannot see an error.
Thanks for checking!

**Comment by parrish** [comment]
Fixed now.  Redis was slightly out of sync -- which becomes more of a problem when a group nears completion ("cold-fire").

**Comment by jwidness** [comment]
Can you check the redis for Dawn Bird, I'm getting the out of data message again. Thanks!

**Comment by AnLand** [comment]
@srallen @parrish Hi, we're having again the "We're out of data" message, but still active subjects. I suspect that it is Dawn Bird that is out of data. Could you fix the wrong display of the message please? Thanks!

**Comment by parrish** [comment]
Should be fixed now.

**Comment by jwidness** [comment]
Looks good, thanks for the quick response!
