### ISSUE TITLE
Skip previews, load directly videos?

### ISSUE THREAD

**Issue by AnLand** [zooniverse/chimpandsee#127]
Hi, we would like to ask whether it is possible to skip the nine previews-part of the annotation interface completely and always directly load the video. We think that the small previews, which only show parsed screenshots from the video, lead to many blank classifications when an animal is actually present. This causes problems with too early retirement of videos and influences the majority rule for determining the species present. We discussed this issue also with the science team. They support this request.

Would this be possible? If we can do anything to help, please let me know. Thanks a lot!

**Comment by aliburchard** [comment]
This is really interesting. Have you looked at the data to assess the rates of false negatives based on preview classifications? Multiple people see the previews, and preview images are different for everyone who sees a subject, so that should protect against most false empties, but perhaps the retirement rules need revisiting. 

Note that changing the retirement rules could change how you aggregate the data, so such changes really need to be data driven. Can you evaluate the data to see how many false negatives are coming from the previews?

**Comment by AnLand** [comment]
@aliburchard It is not necessary the case that multiple people see the previews as there is the option to permanently skip the previews and directly load the video. I assume that most regular volunteers use this option as the video loads faster, the previews are really small, movement of an animal makes it better recognizable in a video, and in the end they have to load the video anyway if they want to annotate an animal. From the previews, one can only classify "nothing here".
So, one could also assume that newer volunteers - who are also less experienced - use the previews more and might influence the classification results additionally.
This is not based on any data quality assessment, but on randomly checking videos for "blanks" and our thought about this.

**Comment by aliburchard** [comment]
When you say this is based on "randomly checking videos for blanks" -- can you tell me what that means? 

I think this definitely warrants looking at the data to see if the previews are actually reducing volunteer accuracy. Also will be good to see how many volunteers use the preview and if that is unevenly distributed across their experience levels.

**Comment by AnLand** [comment]
For randomly checking, I am using either of the following video selections and check for blank classifications in videos containing an animal, just to get a feeling:
1)	the last 20 videos from the Recents’ stream, if diverse enough (it’s not diverse enough since weeks)
2)	the last 20 videos from my own classification (excluding the real „blanks“)
3)	the last 20 retired videos from the primates’ list (= „other (non-primate)“) of that day from one of the open sites

I think the science team can provide better (or better: actual) data. Can we see how many volunteers use the previews and at what point / how often they switch to the video?
