### ISSUE TITLE
Aged Violet site location map not displaying

### ISSUE THREAD

**Issue by jwidness** [zooniverse/chimpandsee#130]
After a classification at Aged Violet, the map doesn't display on the summary page.

**Comment by srallen** [comment]
@jwidness I'm not sure which area on the original map corresponds to the name I'm seeing for that subject group since it doesn't exactly match. Could you let me know which area Aged Violet corresponds to?: http://panafrican.eva.mpg.de/english/where_we_work.php

**Comment by jwidness** [comment]
It's in Region A.
Thanks!

**Comment by srallen** [comment]
Reopening. There's another issue causing the image to fail.

**Comment by srallen** [comment]
@astopy when trying to fetch the `ProjectGroup` for `aged-violet`, it's returning as undefined. I've tried in console `zooniverse.models.ProjectGroup.find("5742e2e257220d001c000001")` and get undefined back. I can fetch another active group, `restless-star` (id: 56c1bcbacf00ff0272000007), successfully.

Relevent code here: https://github.com/zooniverse/chimpandsee/blob/master/app/annotation/summary.cjsx#L38-L44

**Comment by astopy** [comment]
@srallen That's odd. What does it get back from the API? It should be getting https://api.zooniverse.org/projects/chimp/groups/5742e2e257220d001c000001/

**Comment by astopy** [comment]
@srallen Just had a sec to test this, and it seems to load https://api.zooniverse.org/projects/chimp/groups to get the metadata. There are a lot of groups for this project, so aged-violet is on page 2 https://api.zooniverse.org/projects/chimp/groups?page=2

**Comment by eatyourgreens** [comment]
It might be better to call the API route directly, rather than using `ProjectGroup.find()`, eg. https://github.com/zooniverse/sciencegossip/blob/master/overrides.coffee#L168

**Comment by eatyourgreens** [comment]
Looks like the `find` method on that class doesn't call the API at all, just searches through an array of fetched groups, and `fetch` only grabs the first page of results
https://github.com/zooniverse/Zooniverse/blob/master/src/models/base-model.coffee#L18-L21
https://github.com/zooniverse/Zooniverse/blob/master/src/models/project-group.coffee#L14-L34
so, as Adam suggests, the `instances` array is probably just the first page of results.

**Comment by srallen** [comment]
Ah ok, thanks @eatyourgreens and @astopy. I'll rework how the group is being fetched.
