### ISSUE TITLE
Same adjacent videos are repeated

### ISSUE THREAD

**Issue by AnLand** [zooniverse/chimpandsee#132]
This might be a start issue of the new site, but the same small number of adjacent videos seems to be repeated. I individually classified some videos up to three times. Others are classifying the exactly same videos. Usually that is not the case, even with new sites. Maybe more videos need to be activated?

**Comment by mimiarandjelovic** [comment]
We have some videos coming up 3 times now and it seems to be happening at an increasing rate, this certainly is decreasing the rate our videos are being analyzed - can someone look into it please?

**Comment by mimiarandjelovic** [comment]
relevant post: https://talk.chimpandsee.org/#/boards/BCP000000e/discussions/DCP000186b

and collection of some of these videos: https://talk.chimpandsee.org/#/collections/CCPL0000xl

**Comment by srallen** [comment]
@astopy is there anything on the backend we can do to check if there a duplicates in the subject groups of if subjects are being fetched or cached twice? When I have a moment, I'll see if I can replicate on the front end.

**Comment by astopy** [comment]
To figure out whether users are being served the same subject more than once or if there are multiple subjects which have the same videos we're going to need a bit more information:

1. When you see a video for the second time, does it have a different ID or the same ID as the first time? i.e. if you click the talk link, do you end up on a different page or not?
2. If the IDs are different, I'll need a few IDs from videos which are the same so that I can figure out what's happening.
3. If the IDs are the same, then most likely this is a repeat of #98 and the classifications aren't being recorded for some reason.

**Comment by jwidness** [comment]
It's almost always the same ID -- there are a few duplicate videos in the data set with different IDs, but that's quite rare, for example ACP000aydw and ACP000awo1.  These duplicates are not the ones we're talking about when we say we get the same video.  I don't think it's the same problem as #98 though.  It's not giving the out of data response, and it's been going on for much longer than the problem in #98.

**Comment by srallen** [comment]
If you see a repeat happen, could you open up your browser console and let me know if you see errors there? A screenshot is ok. I'm working to replicate and haven't seen a duplicate yet.

**Comment by srallen** [comment]
Ok, just came across one: ACP000f7n7

This video came up in different subject queues. I had been doing a few classifications and refreshing occasionally to switch between the two active groups, restless star and aged violet. I had my console open the whole time and classifying neither time produced an error on the client side that I saw. It's also in my recents twice, with differing `updated_at` timestamps (I also favorited it the second time I saw it):

![screen shot 2016-06-28 at 10 11 23 am](https://cloud.githubusercontent.com/assets/5016731/16420938/d0b0f47e-3d18-11e6-9464-41c46f0201e5.png)
![screen shot 2016-06-28 at 10 11 32 am](https://cloud.githubusercontent.com/assets/5016731/16420942/d38dbe2a-3d18-11e6-92a2-e423674fffc7.png)

**Comment by AnLand** [comment]
Sorry, I wasn't really sure and needed to confirm: I had in the last minutes three repeats (one for the fourth time) and two repetition blanks, e.g. https://talk.chimpandsee.org/#/subjects/ACP000egfy - and there is in my case no error message besides the "mixed content" that is a problem since months.

**Comment by astopy** [comment]
@parrish Could you weigh in on this? Any idea why Ouroboros would be showing subjects to users more than once?

**Comment by parrish** [comment]
Chances are this happened when redis ran out of memory.  The failover is a random database selection of active subjects.

**Comment by astopy** [comment]
Ah, that makes sense. In that case this shouldn't be a regular occurrence.

@AnLand @mimiarandjelovic @jwidness Basically, there was an error that meant the site couldn't check which videos the users had already seen, so it chose some at random instead. This should be very rare... can you confirm that it's not still happening regularly?

**Comment by AnLand** [comment]
At least for the moment it looks better. I did not have an obvious repeat today. I will check a bit more later. (But I have repeats - ocasionally - for more than a year. In all sites, mostly when a site is about to finish.)

**Comment by astopy** [comment]
I'm going to close this for now, but let me know if it happens again and we'll investigate further.
