### ISSUE TITLE
Reporting problematic clip(s), one does not stop playing in Chrome & FF

### ISSUE THREAD

**Issue by ksigler** [zooniverse/chimpandsee#136]
Subjects [ACP000coxj](https://talk.chimpandsee.org/#/subjects/ACP000coxj) through [ACP000coyy](https://talk.chimpandsee.org/#/subjects/ACP000coyy) seem to be corrupted or recorded or processed incorrectly, but only [ACP000coyh](https://talk.chimpandsee.org/#/subjects/ACP000coyh) causes the issue below (so far).

Playing this video in Internet Explorer seems normal.  When playing in Chrome or Firefox, it keeps playing long after the :10 seconds it should.  In Chrome, the blue progress bar (only seen when hovering the clip) on the video player extends beyond the player but eventually stops, while the timer continues.  On the [discussion page](https://talk.chimpandsee.org/#/boards/BCP000000c/discussions/DCP0001hah) for the subject, the progress bar never stops expanding, and as a result, causes the page to continuously widen, with the horizontal scrollbar expanding as the only sign something is going wrong until Chrome crashes.

I put a warning comment on the single clip about the crashing, but can someone take a look into the larger issue?  Thank you!

**Comment by srallen** [comment]
I am seeing the same issues in Chrome and Firefox and it doesn't seem to be an issue with the video player. Either something went wrong in the encoding or something is wrong in the original source file. @astopy do we keep any logs from the encoding process that could be looked at? This is the source of ACP000coyh: https://static.zooniverse.org/www.chimpandsee.org/subjects/56b208d78f7532000191c787/56b208d78f7532000191c787.mp4

**Comment by astopy** [comment]
Unfortunately we don't have logs from the encoding, but it's probably an issue with the original file since it's affecting multiple consecutive subjects. We don't still have the original files but I'll check with the science team.

**Comment by astopy** [comment]
Oh actually, we do still have the files. Downloading them now.

**Comment by srallen** [comment]
Since ACP000coyh is causing play back issues and crashing some browsers, could we pause that subject for now?

**Comment by astopy** [comment]
ACP000coyh is already retired -- looks like a few people marked it as blank so it retired pretty quickly.

**Comment by astopy** [comment]
Ok, looks like there are only 15 other active subjects from the affected videos:

ACP000coxv
ACP000coy2
ACP000coyq
ACP000coxt
ACP000coxk
ACP000coy7
ACP000coye
ACP000coxl
ACP000coyk
ACP000coyu
ACP000coxj
ACP000coy5
ACP000coyn
ACP000coy6
ACP000coyf

I'm just going to go ahead and pause them.
