### ISSUE TITLE
Green Snowflake site chimp ID board button needs new link

### ISSUE THREAD

**Issue by AnLand** [zooniverse/chimpandsee#147]
After you classify a chimp video, the summary page has a button labeled "Site Chimp ID Board" (see image). This button doesn't go to the ID board for the new site Green Snowflake. The link need to be corrected to the URL of the new discussion board. So we should have for Green Snowflake "https://talk.chimpandsee.org/#/boards/BCP000000v" (not the classification interface).

Thanks!

<img width="955" alt="summary_page" src="https://user-images.githubusercontent.com/7421089/28381185-2ee7e90e-6cba-11e7-88f7-d8a98cb5de97.png">

**Comment by AnLand** [comment]
Also, is there a chance to bring the discussion boards in the right order (No. 16 - the new one) at the end and not in the middle of other discussion boards. See attached image: first here No. 16, then others, then older site boards in the correct numbering order. Thanks again.

<img width="863" alt="order_boards" src="https://user-images.githubusercontent.com/7421089/28381374-ef07c4de-6cba-11e7-94eb-6ed783dff7ea.png">

**Comment by astopy** [comment]
Thanks, that's all taken care of now.
