### ISSUE TITLE
Problem in time recordings for comments

### ISSUE THREAD

**Issue by AnLand** [zooniverse/chimpandsee#151]
Hi! Chimp&See has since yesterday a strange glitch in the comments (both video comments and on the discussion boards). First, the comments do have a wrong time stamp from several hours ago. That means, if one makes a comment right now, the time stamps says one commented 2 to five hours ago. The time recorded is not the same deviation for each comment, so that comments are not displayed in the right order (but there is no problem for different comments in the same discussion / for the same video until now).

The problem is probably uncritical for the record, but irritating. As far as I can see, no comments are disappearing. But maybe somebody could look int o it? Thank you!

**Comment by astopy** [comment]
Sorry about that. This looks like a problem at Amazon (where our servers are hosted) which was stopping the servers from keeping their clocks in sync. Hopefully it should be fixed now!

**Comment by astopy** [comment]
Just to note, unfortunately we won't be able to fix the timestamps on comments that have already been posted.
