### ISSUE TITLE
Incorrect image thumbnail for the Other(non-primate) category

### ISSUE THREAD

**Issue by yshish** [zooniverse/chimpandsee#153]
There is an incorrect image thumbnail for the Other (Non-primate) category - it shows a bird of prey, the same image as it shows for the Bird category. 
It confused me when classifying a genet, it made me think I had chosen a wrong category.

Screenshot showing both categories with the same image thumbnail:
![ysh_2018-03-04_16-50-14](https://user-images.githubusercontent.com/7211888/36947502-13fa8b62-1fcd-11e8-83eb-34a8cc3add4d.png)

**Comment by yshish** [comment]
@srallen Can you look at it please? Thank you :)

**Comment by srallen** [comment]
This is working as intended. The image is being reused for non-primate in the previews in the classifier as well as in the field guide. I only have 28 preview animal images, so if it wasn't the bird, it would be another already used non-primate animal: https://github.com/zooniverse/chimpandsee/blob/master/public/assets/chimps-tooltips-sprite.jpg

**Comment by yshish** [comment]
OK, thank you for explaining. Anyway, that fact surprises me because this _Other non-primate_ category isn't meant for birds as they've got their own category. So it doesn't make sense to have it for both categories.

I think there used to be an image example of a genet for that category (not sure though as I haven't been there for a while) but definitely not a bird.

I asked in the C&S Talk whether there have been any changes. Mimi isn't aware of them and asked me to re-open this issue: https://talk.chimpandsee.org/#/boards/BCP0000008/discussions/DCP00029yc?page=1&comment_id=5a9e93a7c6ce933a1d0006d5

Is there anything we could help with? If we provided an image example appropriate for that category, would you be able to add it on the site?

Thank you very much.

**Comment by yshish** [comment]
Ah, I can't see the button for re-opening issues so I guess I haven't got rights to do so.

**Comment by srallen** [comment]
It's been the bird image since the site launched: https://github.com/zooniverse/chimpandsee/commit/67546559d27eef99139b601b9e3ca597b13825a4#diff-5fd934dfc456a2832134a65850d143a0R152

I would prefer if it's going to be changed to plan on the change for the Panoptes version of the project.
