### ISSUE TITLE
Mozilla Firefox update caused some icons to disappear

### ISSUE THREAD

**Issue by AnLand** [zooniverse/chimpandsee#154]
The current Firefox update (61.0) caused some icons to disappear on the annotation interface, I believe. The gray heart icon for the favorites and the "done" icon in the step-wise classification are missing. I attach a screenshot.

<img width="350" alt="2" src="https://user-images.githubusercontent.com/7421089/42121966-1de740e2-7c3a-11e8-85b9-d2d7e851288c.png">

There is also another discussion about issues with video presentation after the last Google Chrome update: https://talk.chimpandsee.org/#/boards/BCP0000008/discussions/DCP0002f1p, but not everybody sees the same and experiences the problem that the play/stop button stays in the middle of the screen in full-screen mode.

Thanks for looking into this!

**Comment by AnLand** [comment]
The icons seem to be back now.

**Comment by srallen** [comment]
@AnLand I've updated to the latest Firefox and I see some of the icons missing as well. The site seems to be taking longer than it should to load in both Chrome and Firefox, so I'm investigating that to see if it's related.

**Comment by srallen** [comment]
Just an update, clearing the cache on the server seems to have improved load times. 

As for the play button in Chrome, I can confirm I see that behavior too where the button remains in full screen mode. This likely changed in the latest update. I'll look to see if it's configurable for the player.

**Comment by srallen** [comment]
We've fixed the slow site loading issue, which I think was causing the issue of the image assets not loading correctly.

The Chrome play bug issue I think is unfortunately a browser issue and I'm not sure of a good code hack around that yet. I've described how to work around it manually in the Talk thread for those users experiencing this behavior.
