### ISSUE TITLE
There's no sound during video playback on Lenovo Yoga tablet, in Chrome

### ISSUE THREAD

**Issue by yshish** [zooniverse/chimpandsee#83]
There's no sound during video playback on Lenovo Yoga tablet, using Chrome. I can see the symbol for turning sound on/off, I can click on it but with no difference. It even doesn't allow me to set the volume. (I can hear any sounds out of Chimp&See).

**Comment by srallen** [comment]
This is a year plus old and difficult to debug since Chrome version is not known. Will reopen if any new reports exist.
