### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by srallen** [zooniverse/chimpandsee#9]
- [ ] Determine hybrid solution using both zooniverse library and react translation component recommended by Brian and used on Panoptes front end.

**Comment by ksigler** [comment]
The Chimp & See team has many people interested in translating the project and would like to move forward.  Is this solution still possible?  Thanks!

**Comment by srallen** [comment]
We'll need to do some research and testing to find out if the react translate component is what we'll need to use to make the translations work and/or the best solution for this. I'm not sure when we'll have time to do this though since we have several high priority projects this month. I'm pinging @trouille so she's aware that the science team is requesting this.

**Comment by mimiarandjelovic** [comment]
We are definitely really interested and ready to go if this can become a reality.

**Comment by srallen** [comment]
Translations is in a beta testing state now on Panoptes and PFE.
