### ISSUE TITLE
Screenshots (No. 0 to 15) unavailable

### ISSUE THREAD

**Issue by AnLand** [zooniverse/chimpandsee#96]
Sorry, another issue with the new videos (but it worked yesterday!), the screenshots are unavailable at least for Dawn Bird. These are crucial for the discussion boards. Could somebody look into that, please?

Error message:
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>285C9EC908A96E45</RequestId><HostId>Jcz/QuOr7EjOmeTykf5/lsNerWxKtVMGg1zHfqzfSoxaknfiqQWZ/Qtqzi/nl5fwP+mqUDP9GJE=</HostId></Error>

Thank you!

**Comment by astopy** [comment]
Could you let me know what URL gave you that error message?

Thanks.

**Comment by AnLand** [comment]
Here an example.
URL: https://static.zooniverse.org/www.chimpandsee.org/subjects/56c1e2e2cf00ff2466008438/previews/56c1e2e2cf00ff2466008438_10.jpg

Error message: "<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>C26B811FABC9FDAC</RequestId><HostId>lmIpEqJK9ewj3/5jg/9SIRaQlKmbMtOZ3oAy29xqsjn6vCaNZOJghlfk1kpkLc4n</HostId></Error>"

**Comment by astopy** [comment]
Thanks. It looks like the subject ID in the URL isn't valid -- we had an issue with some of those being generated incorrectly, but I thought I'd corrected them all. Where did you see that one?

**Comment by yshish** [comment]
It seems to be a problem of DawnBird location videos http://talk.chimpandsee.org/#/subjects/ACP0007hym or http://talk.chimpandsee.org/#/subjects/ACP0007hia
and of LingeringShape videos
http://talk.chimpandsee.org/#/subjects/ACP0007esg

because DryLake screen shots do work for me.

**Comment by AnLand** [comment]
It seems to be a problem of all newly loaded videos. Interestingly, it worked on Monday e.g. for this video (I posted screenshots), but even here it does not work anymore: https://static.zooniverse.org/www.chimpandsee.org/subjects/56c1e266cf00ff2466006dbe/previews/56c1e266cf00ff2466006dbe_12.jpg Message: <Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>85DD944A9E818DD0</RequestId><HostId>6CpMAoLH3BlNrpK6Dj0Io7leyjE4K3LvxmWdwLGQDDo2rd6EmuQhG6PbLte7pu6wQEDkVgcZ9Po=</HostId></Error>

**Comment by srallen** [comment]
@astopy I think there are some subjects that still have ID issues. I just came across this subject while trying to debug some other issues that is getting access denied errors on Talk as well as some 403 errors in the console for the classifier itself:

```
GET https://static.zooniverse.org/www.chimpandsee.org/subjects/56b211548f75320001932005/previews/56b211548f75320001932005_8.jpg 403 (Forbidden)
GET https://static.zooniverse.org/www.chimpandsee.org/subjects/56b211548f75320001932005/previews/56b211548f75320001932005_6.jpg 403 (Forbidden)
GET https://static.zooniverse.org/www.chimpandsee.org/subjects/56b211548f75320001932005/previews/56b211548f75320001932005_10.jpg 403 (Forbidden)
GET https://static.zooniverse.org/www.chimpandsee.org/subjects/56b211548f75320001932005/previews/56b211548f75320001932005_14.jpg 403 (Forbidden)
GET https://static.zooniverse.org/www.chimpandsee.org/subjects/56b211548f75320001932005/previews/56b211548f75320001932005_12.jpg 403 (Forbidden)
GET https://static.zooniverse.org/www.chimpandsee.org/subjects/56b211548f75320001932005/previews/56b211548f75320001932005_15.jpg 403 (Forbidden)
```

Talk subject page: http://talk.chimpandsee.org/#/subjects/ACP00084qp
preview images 4-15 get access denied errors

**Comment by srallen** [comment]
Another that fails with its previews and video: http://talk.chimpandsee.org/#/subjects/ACP0007gg1

403 errors in the classifier and these on Talk:

`Failed to load resource: the server responded with a status of 403 (Forbidden)` 
for https://static.zooniverse.org/www.chimpandsee.org/subjects/56b1efa18f7532000190381c/previews/56b1efa18f7532000190381c_0.jpg

`Failed to load resource: the server responded with a status of 416 (Requested Range Not Satisfiable)` for the video: https://static.zooniverse.org/www.chimpandsee.org/subjects/56b1efa18f7532000190381c/56b1efa18f7532000190381c.mp4

**Comment by astopy** [comment]
@srallen For ACP00084qp those aren't the right preview links... which page did those URLs come from? (The talk page seems to have the right ones.)

Not sure what's happened with ACP0007gg1. Looking into that now.

**Comment by srallen** [comment]
@astopy, for ACP00084qp I grabbed those errors from the console when the classifier got stuck loading the subject in the classifier itself. When I saw that happen, I checked its talk page and was getting access  denied errors there too, but checking today it looks like they're working now.

**Comment by srallen** [comment]
I found another subject with broken previews:

http://talk.chimpandsee.org/#/subjects/ACP000ck02

Images 9-15 get access denied errors.

**Comment by AnLand** [comment]
@srallen But the video is only 8 seconds long here. The other screenshots cannot be available.

**Comment by srallen** [comment]
@AnLand good catch. The videos should be 15s long, so that means something went wrong with the encoding of this one?

**Comment by AnLand** [comment]
Don't think so, the field team might have changed the SD card and "interrupted" the recording with this. (My interpretation.)

**Comment by srallen** [comment]
Ok, the front end client is expecting at least 9 images to use for the previews, so we may want to either fix the subject so that there's at least 9 or I could modify the front end to show a placeholder if 9 images are not available. I'd rather do the former than the latter if possible.

**Comment by astopy** [comment]
Yeah, in this case the original video must have been shorter than normal. If the encoding had failed there’d be no previews at all I think. (Though saying that there are almost certainly others which are broken that we haven’t found yet; I’m still working on a fix for that.)

I’m not sure if generating more images for short videos is really viable — assuming it’s not just this one, we’d have to somehow find all the others first which might not be easy.

**Comment by AnLand** [comment]
@astopy and @srallen: occasionally videos are shorter than 15 seconds, mostly - as far as I can see while classifying - when the field team is maintaining the camera and stops recording. I do not know whether one can see in the video structure in which videos that might be the case and filter them out. But yes, there are several of them.

**Comment by srallen** [comment]
@AnLand Ok, I'll think I can at least add in checking the length of the array of previews and making sure there is at least 9 and if not, adding in a placeholder. The interface gets stuck on the loading spinner with this particular subject since there were only 8 previews. 

Would a placeholder like this be ok?:

![placeholder-example](https://cloud.githubusercontent.com/assets/5016731/13640321/cb5eed32-e5d9-11e5-94bc-56a1fcd4f0f7.png)

**Comment by AnLand** [comment]
@srallen Yes, that would be great. (I talked to the science team, they agree, too.)

**Comment by astopy** [comment]
The subject ACP0007gg1 seems to have been created from a video which ffmpeg can't decode, so I assume the original file was just corrupt somehow. I've updated the scripts so database entries won't be created to corrupt files next time

I've run a script against every subject in the database to find any other similar subjects. There were twelve in total (including ACP0007gg1, so three original videos), and I've paused them now.

**Comment by srallen** [comment]
@astopy Just curious about the errors you were getting with the corrupted videos. I'll be processing videos for Mammoth Bats soon and have used ffprobe with them and had a few videos with some unusual log messages. What kind of errors did these have so I know what to look for?

**Comment by astopy** [comment]
Sure, this is the error:

```
ffmpeg version N-53570-gc411e90-static http://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 5.3.1 (Debian 5.3.1-11) 20160307
  configuration: --enable-gpl --enable-version3 --disable-shared --disable-debug --enable-runtime-cpudetect --enable-libmp3lame --enable-libx264 --enable-libx265 --enable-libwebp --enable-libspeex --enable-libvorbis --enable-libvpx --enable-libfreetype --enable-fontconfig --enable-libxvid --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libtheora --enable-libvo-amrwbenc --enable-gray --enable-libopenjpeg --enable-libopus --enable-libass --enable-gnutls --enable-libvidstab --enable-libsoxr --enable-frei0r --enable-libfribidi --disable-indev=sndio --disable-outdev=sndio --enable-librtmp --enable-libmfx --cc=gcc
ffmpeg version N-53570-gc411e90-static http://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 5.3.1 (Debian 5.3.1-11) 20160307
  configuration: --enable-gpl --enable-version3 --disable-shared --disable-debug --enable-runtime-cpudetect --enable-libmp3lame --enable-libx264 --enable-libx265 --enable-libwebp --enable-libspeex --enable-libvorbis --enable-libvpx --enable-libfreetype --enable-fontconfig --enable-libxvid --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libtheora --enable-libvo-amrwbenc --enable-gray --enable-libopenjpeg --enable-libopus --enable-libass --enable-gnutls --enable-libvidstab --enable-libsoxr --enable-frei0r --enable-libfribidi --disable-indev=sndio --disable-outdev=sndio --enable-librtmp --enable-libmfx --cc=gcc
  libavutil      55. 19.100 / 55. 19.100
  libavcodec     57. 28.103 / 57. 28.103
  libavformat    57. 28.102 / 57. 28.102
  libavdevice    57.  0.101 / 57.  0.101
  libavfilter     6. 39.102 /  6. 39.102
  libswscale      4.  0.100 /  4.  0.100
  libswresample   2.  0.101 /  2.  0.101
  libpostproc    54.  0.100 / 54.  0.100
  libavutil      55. 19.100 / 55. 19.100
  libavcodec     57. 28.103 / 57. 28.103
  libavformat    57. 28.102 / 57. 28.102
  libavdevice    57.  0.101 / 57.  0.101
  libavfilter     6. 39.102 /  6. 39.102
  libswscale      4.  0.100 /  4.  0.100
  libswresample   2.  0.101 /  2.  0.101
  libpostproc    54.  0.100 / 54.  0.100
[mjpeg @ 0x50c7f60] bits 255 is invalid
bits 255 is invalid     Last message repeated 8 times
    Last message repeated 112 times
[avi @ 0x43740a0] decoding for stream 0 failed
[avi @ 0x43740a0] Could not find codec parameters for stream 0 (Video: mjpeg (MJPG / 0x47504A4D), none(bt470bg/unknown/unknown), 720x480, lossless): unspecified pixel format
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Guessed Channel Layout for  Input Stream #0.1 : mono
Input #0, avi, from '/processing/zooniverse-data/chimps/Liberia_Sapo/Sapo_E4/Lib_C_vid33_E4_20120523/PICT0002.AVI':
  Duration: 00:01:00.83, start: 0.000000, bitrate: 9169 kb/s
    Stream #0:0: Video: mjpeg (MJPG / 0x47504A4D), none(bt470bg/unknown/unknown), 720x480, lossless, 30 fps, 30 tbr, 30 tbn, 30 tbc
    Stream #0:1: Audio: pcm_mulaw ([7][0][0][0] / 0x0007), 44100 Hz, 1 channels, s16, 352 kb/s
[buffer @ 0x4373fa0] Unable to parse option value "-1" as pixel format
    Last message repeated 1 times
[buffer @ 0x4373fa0] Error setting option pix_fmt to value -1.
[graph 0 input from stream 0:0 @ 0x43772c0] Error applying options to the filter.
Error opening filters!
consumer.rb:104:in `system': can't convert Enumerator into String (TypeError)
        from consumer.rb:104:in `block (3 levels) in <main>'
    Last message repeated 73 times
[avi @ 0x50c70a0] decoding for stream 0 failed
[avi @ 0x50c70a0] Could not find codec parameters for stream 0 (Video: mjpeg (MJPG / 0x47504A4D), none(bt470bg/unknown/unknown), 720x480, lossless): unspecified pixel format
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Guessed Channel Layout for  Input Stream #0.1 : mono
Input #0, avi, from '/processing/zooniverse-data/chimps/Liberia_Sapo/Sapo_A2/Lib_C_vid32_A2_20120526/PICT0002.AVI':
  Duration: 00:01:00.70, start: 0.000000, bitrate: 4742 kb/s
    Stream #0:0: Video: mjpeg (MJPG / 0x47504A4D), none(bt470bg/unknown/unknown), 720x480, lossless, 30 fps, 30 tbr, 30 tbn, 30 tbc
    Stream #0:1: Audio: pcm_mulaw ([7][0][0][0] / 0x0007), 44100 Hz, 1 channels, s16, 352 kb/s
[buffer @ 0x50c6fa0] Unable to parse option value "-1" as pixel format
```

**Comment by AnLand** [comment]
@astopy Please delete file name from error message. Thanks!

**Comment by astopy** [comment]
@AnLand Oops, sorry, I've edited it now.
